### ISSUE TITLE
negative value in rainfall intensity

### ISSUE THREAD

**Issue by Pei4579** [NTU-CompHydroMet-Lab/pyBL#15]
Plenty are negative when I print out the rainfall intensity of each scale. While I looked into them, they are the values were very tiny such as -3.700743415417188e-17, -1.9660199394403812e-17, -2.0816681711721685e-17, or -2.3129646346357426e-17.
*I'm reading the theta from the file "5Y_1_Theta.csv"
[neg.zip](https://github.com/NTU-CompHydroMet-Lab/pyBL/files/14293858/neg.zip)

**Comment by KilinW** [comment]
It has been solved. 
The reason that we have those small negative number is due to a lot of floating point operation when we construct the IndexSnapShot. Now we will force all negative value to be positive.
See the latest commit in dev1 branch.
